---
- name: daemon reload
  systemd:
    daemon_reload: yes
  when: docker_service_manage | bool

- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool
